baseURL = "https://shafik.xyz"
title = "Shafik's blog"
theme = "shafik.xyz"
pygmentsCodeFences = true
pygmentsUseClasses = true
copyright = "Mohd. Shafikur Rahman"
enableGitInfo = true
enableRobotsTXT = true

[googleAnalytics]
trackingId = "G-LW8GG2RMQG"

[params]
githubRepoUrl = "https://github.com/shafikshaon/shafik.xyz"
trackingId = "G-LW8GG2RMQG"
author = "Shafikur Rahman"
description = "ğŸ‘‹ Software Engineer | ğŸŒ Dhaka, Bangladesh | Python, Go, JavaScript | ğŸš€ Building solutions"
github = "shafikshaon"
facebook = ""
twitter = "shafikshaon"
linkedin = "shafikshaon"
instagram = ""
tumblr = ""
stackoverflow = "4751726"
email = "shafikshaon@gmail.com"
url = "https://shafik.xyz"
rss = true
keywords = "blog, software engineer, django, golang, go"
lastmod = true
userStatusEmoji = "ğŸ˜€"
favicon = "/images/github.webp"
avatar = "/images/avatar.webp"
headerIcon = "/images/GitHub-Mark-Light-32px.webp"
location = "Dhaka"
enableGitalk = false

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
tag = "tags"
series = "series"
category = 'categories'